depot/config/routes.rb
Rails.application.routes.draw do
  resources :genres do
    collection do
      get '/', to: 'genres#index'
      match '/new', to: 'genres#create', via: [:get, :post]
    end
    member do
      get '/', to: 'genres#show'
      match '/edit', to: 'genres#edit', via: [:get, :patch]
      match '/delete', to: 'genres#delete', via: [:get, :delete]
    end
  end

  resources :orders, except: [:edit, :destroy, :update] do
    member do
      get 'ship'
    end
    collection do
      get 'filter'
    end
  end

  devise_for :users
  resources :line_items, only: [:create]
  resources :carts, only: [:destroy]
  root 'store#index', as: 'store_index'

  get 'marker', to: 'marker#index'
  post 'marker/update', to: 'marker#update'

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

depot/app/views/layouts/_navbar.html.erb
<script>
    const openCart = () => {
        $('#wrapper').removeClass('toggled');
        localStorage.setItem('revealed?', 'true')
        const cart_down_icon = `<i class="fa fa-shopping-cart" aria-hidden="true"></i>
          <i class="fa fa-chevron-left" aria-hidden="true"></i>`
        $('.toggle-cart-btn').html(cart_down_icon);
        $('.toggle-cart-btn').off('click').on('click',closeCart);
    }
    const closeCart = () => {
        $('#wrapper').addClass('toggled');
        localStorage.setItem('revealed?', 'false')
        const cart_right_icon = `<i class="fa fa-shopping-cart" aria-hidden="true"></i>
          <i class="fa fa-chevron-right" aria-hidden="true"></i>`;
        $('.toggle-cart-btn').html(cart_right_icon);
        $('.toggle-cart-btn').off('click').on('click', openCart);
    }
  $(document).on('turbolinks:load', () => {
      if (localStorage.getItem('revealed?') === 'true') {
          openCart();
      } else {
          closeCart();
      }
  })

</script>
<nav class="navbar fixed-top navbar-expand-lg bg-dark border-bottom" id="navbar">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if @cart %>
            <button class="btn toggle-cart-btn">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i>
              <i class="fa fa-chevron-left" aria-hidden="true"></i>
            </button>
          <% end %>
        </li>
      <li class="nav-item"><%= link_to 'Shop', store_index_url, class: "nav-link" %></li>
      <% if current_user.present? %>
        <li class="nav-item"><%= link_to 'Orders', orders_url, class: "nav-link"%></li>
        <li class="nav-item"><%= link_to 'Products', products_url, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Genres', genres_url, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Account', edit_user_registration_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

depot/app/views/layouts/_notifications.html.erb
<% if alert %>
  <div class="alert alert-danger" role="alert" id="alert">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <strong class="alert-content"><%= alert %></strong>
  </div>
<% end %>
<% if notice %>
  <div class="alert alert-info" role="alert" id="notice">
    <button type="button" class="close" data-dismiss="alert">x</button>
    <strong class="notice-content"><%= notice %></strong>
  </div>
<% end %>

depot/app/views/layouts/_sidebar.html.erb
<div class="sidebar-heading"><%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf', align: "middle" %></div>
<div id="cart">
  <% if @cart %>
    <%= render @cart %>
  <% else %>
    <script>
        $("#wrapper").addClass("toggled");
        localStorage.setItem('revealed?', 'false')
    </script>
  <% end %>
</div>

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--    Datetime picker-->
    <%= stylesheet_link_tag "https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" %>
    <%= javascript_include_tag "https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" %>

  </head>

  <body class ='<%= controller.controller_name %>'>
    <div id="wrapper" class="d-flex toggled">
      <div id="sidebar-wrapper" class="bg-light border-right">
        <%= render 'layouts/sidebar' %>
      </div>
        <div id="page-content-wrapper">
          <div id="navbar">
            <%= render 'layouts/navbar' %>
          </div>
          <div class="container" id="main">
            <div id="notifications">
              <%= render 'layouts/notifications' %>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>