depot/config/routes.rb
Rails.application.routes.draw do
  resources :genres do
    collection do
      get '/', to: 'genres#index'
      match '/new', to: 'genres#create', via: [:get, :post]
    end
    member do
      get '/', to: 'genres#show'
      match '/edit', to: 'genres#edit', via: [:get, :patch]
      match '/delete', to: 'genres#delete', via: [:get, :delete]
    end
  end

  resources :orders, except: [:edit, :destroy, :update] do
    member do
      get 'ship'
    end
    collection do
      get 'filter'
    end
  end

  devise_for :users
  resources :line_items, only: [:create]
  resources :carts, only: [:destroy]
  root 'store#index', as: 'store_index'

  get 'marker', to: 'marker#index'
  post 'marker/update', to: 'marker#update'

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

depot/app/models/cart.rb
class Cart < ApplicationRecord
  # Each cart can be associated to many line_items, and the line_items are
  # destroyed if the cart is destroyed
  has_many :line_items, dependent: :destroy

  # Checks if the Product is already a LineItem, if it is, increment quantity associated
  # with the LineItem, else create a new LineItem with quantity 1.
  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

depot/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_cart, only: %i[ show edit update destroy ]
  # If there's a RecordNotFound exception, call invalid_cart
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempted to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
end

depot/app/helpers/carts_helper.rb
module CartsHelper
end

depot/app/views/carts/_cart.html.erb
<h2>Your Cart</h2>
<div>
  <table>
    <%= render(cart.line_items) %>
    <tr class="total_line">
      <td colspan="2">Total</td>
      <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
    </tr>
  </table>
</div>
<div>
  <div class="row cart-button">
    <%= button_to 'Checkout', new_order_path, method: :get, class:"checkout-btn"%>
  </div>
  <div class="row cart-button">
    <%= button_to 'Empty cart', cart, method: :delete, class: "empty-cart-btn",
                  data: { confirm: 'Are you sure?' } %>
  </div>
</div>

depot/app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

depot/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

depot/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="title">Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

depot/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

depot/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @cart %>