depot/config/routes.rb
Rails.application.routes.draw do
  resources :genres do
    collection do
      get '/', to: 'genres#index'
      match '/new', to: 'genres#create', via: [:get, :post]
    end
    member do
      get '/', to: 'genres#show'
      match '/edit', to: 'genres#edit', via: [:get, :patch]
      match '/delete', to: 'genres#delete', via: [:get, :delete]
    end
  end

  resources :orders, except: [:edit, :destroy, :update] do
    member do
      get 'ship'
    end
    collection do
      get 'filter'
    end
  end

  devise_for :users
  resources :line_items, only: [:create]
  resources :carts, only: [:destroy]
  root 'store#index', as: 'store_index'

  get 'marker', to: 'marker#index'
  post 'marker/update', to: 'marker#update'

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

depot/app/models/product.rb
class Product < ApplicationRecord
  # Each product can be referenced by many line_items.
  has_many_attached :product_images
  has_many :line_items, dependent: :delete_all
  has_many :orders, through: :line_items
  has_many :genres
  belongs_to :user
  has_many :best_seller_rankings
  accepts_nested_attributes_for :best_seller_rankings, allow_destroy: true,
                                reject_if: lambda {|ranking| ranking[:category].blank? or ranking[:rank].blank? }

  validates :title, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validate :acceptable_image

  def acceptable_image
    return unless product_images.attached?

    unless product_images.all? { |image| image.byte_size <= 3.megabyte }
      errors.add(:product_images, "contain an image that is too big")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    unless product_images.all? { |image| acceptable_types.include?(image.content_type) }
      errors.add(:product_images, "must be a JPG, JPEG or PNG")
    end
  end

  def self.get_all_products_less_than_ten_dollars
    Product.where("price < ?", 10)
  end

  def get_shortened_description
    if description.length > 300
      short_description = description[0..297] + '...'
      ActionController::Base.helpers.sanitize(short_description)
    else
      description
    end
  end

  def genres_if_not_exist(genre_names)
    genre_array = []
    genre_names.each do |genre_name|
      genres_with_same_name = genres.where(name: genre_name.downcase)
      # Should only have 1 record, if any.
      if genres_with_same_name.size > 0
        genre_array << genres_with_same_name.first
      else
        yield(genre_array, genre_name)
      end
    end
    self.genres.replace(genre_array)
  end

  def new_genres_if_not_exist(genre_names)
    genres_if_not_exist(genre_names) { |genre_array, genre_name| genre_array << genres.new(name: genre_name.downcase) }
  end

  def create_genres_if_not_exist(genre_names)
    genres_if_not_exist(genre_names) { |genre_array, genre_name| genre_array << genres.create(name: genre_name.downcase) }
  end

  private
  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

end

depot/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_product_and_check_owner, only: %i[ edit update destroy ]
  before_action :set_cart

  # GET /products or /products.json
  def index
    set_products
  end

  # GET /products/1 or /products/1.json
  def show
    set_product
  end

  # GET /products/new
  def new
    @product = Product.new
    set_genre_names
  end

  # GET /products/1/edit
  def edit
    set_genre_names
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params.except(:genre_names))
    @product.user_id = current_user.id
    new_clean_up_genre_param

    respond_to do |format|
      if @product.save
        set_products
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.js { render :update}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      update_clean_up_genre_aram
      if @product.update(product_params.except(:genre_names))
        puts "SAVED"
        puts @product
        puts @product.genres.size
        @products = Product.all
        ActionCable.server.broadcast 'products',
                                     html: render_to_string('store/index', layout: false)
        set_products
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.js
        format.json { render :show, status: :ok, location: @product }

      else
        set_genre_names
        format.html { render :edit, status: :unprocessable_entity }
        format.js{ render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    respond_to do |format|
      is_destroyed = @product.destroy
      user_products_getter = Thread.new { Thread.current[:output] = set_products }
      user_products_getter.join
      @products = user_products_getter[:output]

      if is_destroyed
        format.html { redirect_to products_url, notice: "Product was successfully deleted." }
        format.js { render 'update.js.erb'}
        format.json { head :no_content }
      else
        @notice = "Cannot delete product, it is being referenced by a line item."
        flash.now[:notice] = @notice
        format.html { redirect_to products_url }
        format.js { render 'update.js.erb', status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_and_check_owner
      begin
        @product = Product.find(params[:id])
        if @product.user != current_user
          unauthorised_access
        end
      rescue ActiveRecord::RecordNotFound
        unauthorised_access
      end
    end

    def set_product
      begin
        @product = Product.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        unauthorised_access
      end
    end

  # Get all unique genre names used by all products for the user to choose from
    def set_genre_names
      @genre_names = Genre.distinct.pluck(:name)
    end

    def set_products
      @products = Product.includes('user').where(users: current_user).order(:title)
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :genre_names => [], :product_images => [],
                                      :best_seller_rankings_attributes => [:id, :category, :rank, :_destroy])
    end

    def unauthorised_access
      flash[:alert] = "You are not authorised to handle product id:#{params[:id]}"
      flash.keep
      redirect_to products_url
    end

    # Use new to create new genres and attach it to the new product and save it together with the product
    def new_clean_up_genre_param
      filter_genres_empty_string = params[:product][:genre_names].select{ |genre_name| genre_name != "" }
      @product.new_genres_if_not_exist(filter_genres_empty_string)
    end

    # Creates and saves genres and attach them to the product.
    def update_clean_up_genre_aram
      filter_genres_empty_string = params[:product][:genre_names].select{ |genre_name| genre_name != "" }
      @product.create_genres_if_not_exist(filter_genres_empty_string)
    end
end

depot/app/helpers/products_helper.rb
module ProductsHelper
end

depot/app/views/products/_best_seller_ranking_fields.html.erb
<div class="nested-fields">
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.number_field :rank %>
  <%= link_to_remove_association "Remove ranking", f %>
</div>

depot/app/views/products/_form.html.erb
<script>
  $(document).on('turbolinks:load', () => {
      $('.select-genre').select2({
          tags: true,
      })
  })
</script>

<%= form_with(model: product, local: false) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :title %></strong>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <strong><%= form.label :description %></strong>
    <%= form.text_area :description, rows: 10, cols: 60, class:"form-control" %>
  </div>


  <div class="row">
    <div class="field col-md-6">
      <strong><%= form.label :genres %></strong>
<!--      Options are all existing genre names and selected are current genres of the product-->
      <%= form.select :genre_names,
                      options_for_select(@genre_names, selected: @product.genres.map {|genre| genre.name}),
                      {}, class: "select-genre form-control", multiple: true %>
    </div>
    <div class="field col-md-6">
      <strong><%= form.label :price %></strong>
      <%= form.text_field :price, class:"form-control" %>
    </div>
  </div>

  <strong><label>Best seller rankings</label></strong>
  <div id="best-seller-rankings">
    <%= form.fields_for :best_seller_rankings do |ranking| %>
      <%= render 'best_seller_ranking_fields', f: ranking %>
    <% end %>
    <%= link_to_add_association 'Add ranking', form, :best_seller_rankings %>
  </div>

  <div class="field image-carousel form-carousel">
    <%= render 'products/image_carousel' %>
  </div>

  <div class="field">
    Product images: click to download
  </div>

  <div class="field">
    <%= form.file_field :product_images, multiple: true %>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-secondary submit-btn" %>
  </div>
<% end %>

depot/app/views/products/_image_carousel.html.erb
<% if @product.product_images.attached? %>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <% for i in 1..@product.product_images.size - 1 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>"></li>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% i = 0 %>
      <% @product.product_images.each do |image| %>
        <% if i == 0 %>
          <div class="carousel-item active">
            <%= link_to image_tag(image, class: "d-block product-image"), image, download: "product_image" %>
          </div>
        <% else %>
          <div class="carousel-item">
            <%= link_to image_tag(image, class: "d-block product-image"), image, download: "product_image" %>
          </div>
        <% end %>
        <% i += 1 %>
      <% end %>
    </div>
    <a class="carousel-control-prev carousel-control" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next carousel-control" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% else %>
  <div id="carouselExampleControls" class="carousel slide no-image" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active d-flex justify-content-center align-content-center h-100">
        No image available
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
<% end %>

depot/app/views/products/_product.html.erb
<tr>
  <td>
    <%= product.id %>
  </td>
  <td>
    <%= product.title %>
  </td>
  <td>
    <%= truncate(strip_tags(product.description), length: 400) %>
  </td>
  <td>
    $<%= number_with_precision(product.price, precision: 2, delimiter: ',') %>
  </td>
  <td class="list_actions">
    <%= link_to 'Show', product %><br/>
    <%= link_to 'Edit', edit_product_path(product) %><br/>
    <%= link_to 'Destroy', product, method: :delete, remote: true,
                data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

depot/app/views/products/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-10" id="product-form-wrapper">
    <h1 id="title">Edit Product</h1>
    <div id="form"><%= render 'form', product: @product %></div>
    <%= link_to 'Back', products_url, method: :get %>
  </div>
</div>

depot/app/views/products/edit.js.erb
$("#form").html("<%=j render 'form', product: @product %>")

depot/app/views/products/index.html.erb
<h1 id="title">Your Products</h1>
<div class="row justify-content-end">
  <%= button_to new_product_path, class:"btn btn-success", id: "add-product-btn", method: :get do %>
    <i class='fas fa-plus-square'></i> New
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <table id="products-datatable" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th class="header">Id</th>
          <th class="header">Title</th>
          <th class="header">Description</th>
          <th class="header">Price</th>
          <th class="header">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
  </div>
</div>
<script>
    $(document).on('turbolinks:load', function() {
        if (! $.fn.DataTable.isDataTable('#products-datatable')) {
            $('#products-datatable').DataTable({
                scrollY: "600px",
                scrollX: true,
                fixedColumns: {
                    leftColumns: 2
                },
                select: {
                    style: 'single',
                    selector: 'td:not(:last-child)'
                },
            })
            const table = $('#products-datatable').DataTable()
            table.on('draw', () => {
                table.columns.adjust().draw();
            })
            table.on('select', (e, dt, type, index) => {
                console.log(table.rows(index).data().toArray()[0][0])
                const product_id = table.rows(index).data().toArray()[0][0]
                Turbolinks.visit('<%= products_url %>' + '/' + product_id)
            });
        }
    });
    $(document).ready(() => {
        document.addEventListener("turbolinks:before-cache", function() {
            if ($.fn.DataTable.isDataTable('#products-datatable')) {
                $('#products-datatable').DataTable().destroy();
            }
        });
    })
</script>

depot/app/views/products/new.html.erb
<div class="row justify-content-center">
  <div class="col-lg-10" id="new-product-form">
    <h1 id="title">New Product</h1>
    <div id="form"><%= render 'form', product: @product %></div>
    <%= link_to 'Back', products_url, method: :get %>
  </div>
</div>

depot/app/views/products/new.js.erb
$("#form").html("<%=j render 'form', product: @product %>")

depot/app/views/products/show.html.erb
<h1 id="title"><%= @product.title %></h1>
<div class="row product-display">
  <div class="col-4 image-carousel">
    <%= render 'products/image_carousel' %>
  </div>
  <div class="col-8">
    <h5 id="seller-line">Seller: <%= @product.user.name %></h5>
    <p><%= sanitize(@product.description) %></p>
    <% if @product.best_seller_rankings.size > 0 %>
      <b>Best seller rankings:</b>
      <ul>
        <% @product.best_seller_rankings.each do |ranking| %>
          <li><%= ranking.category %>: <%= number_with_precision(ranking.rank, precision: 0, delimiter: ',') %></li>
        <% end %>
      </ul>
    <% end %>
    <p class="btn w-100 px-4 text-center mx-auto">
      <%= button_to(line_items_path(product_id: @product), {remote: true, class: "btn btn-warning add-to-cart-btn"}) do %>
        Add to cart <i class='fa fa-cart-plus' aria-hidden='true'></i>
      <% end %>
    </p>
  </div>
</div>

depot/app/views/products/update.js.erb
var body = `
<h1 id="title">Your Products</h1>
<div class="row justify-content-end">
  <%= button_to new_product_path, class:"btn btn-success", id: "add-product-btn", method: :get do %>
    <i class='fas fa-plus-square'></i> New
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <table id="products-datatable" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th class="header">Id</th>
          <th class="header">Title</th>
          <th class="header">Description</th>
          <th class="header">Price</th>
          <th class="header">Actions</th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
  </div>
</div>
`


$("#main").html(body);
$("#notifications").html('<%=j render '/layouts/notifications', locals: { notice: flash[:notice], alert: flash[:alert]} %>')
if (! $.fn.DataTable.isDataTable('#products-datatable')) {
    $('#products-datatable').DataTable({
        scrollY: "600px",
        scrollX: true,
        fixedColumns: {
            leftColumns: 2
        },
        select: {
            style: 'single',
            selector: 'td:not(:last-child)'
        },
    })
    const table = $('#products-datatable').DataTable()
    table.on('draw', () => {
        table.columns.adjust().draw();
    })
    table.on('select', (e, dt, type, index) => {
        console.log(table.rows(index).data().toArray()[0][0])
        const product_id = table.rows(index).data().toArray()[0][0]
        Turbolinks.visit('<%= products_url %>' + '/' + product_id)
    });
}