depot/config/routes.rb
Rails.application.routes.draw do
  resources :genres do
    collection do
      get '/', to: 'genres#index'
      match '/new', to: 'genres#create', via: [:get, :post]
    end
    member do
      get '/', to: 'genres#show'
      match '/edit', to: 'genres#edit', via: [:get, :patch]
      match '/delete', to: 'genres#delete', via: [:get, :delete]
    end
  end

  resources :orders, except: [:edit, :destroy, :update] do
    member do
      get 'ship'
    end
    collection do
      get 'filter'
    end
  end

  devise_for :users
  resources :line_items, only: [:create]
  resources :carts, only: [:destroy]
  root 'store#index', as: 'store_index'

  get 'marker', to: 'marker#index'
  post 'marker/update', to: 'marker#update'

  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

depot/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  def total_price
    product.price * quantity
  end
end

depot/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  skip_before_action :authenticate_user!
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    # Find the Product with the same product_id as provided in params.
    product = Product.find_by(id: params[:product_id])

    # Add a line item of the product to the cart of the session.
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.select(:id, :shipped, :product_id, :order_id, :quantity).where(id: params[:id]).first
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :shipped)
    end
end

depot/app/helpers/line_items_helper.rb
module LineItemsHelper
end

depot/app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

depot/app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item">
<% else %>
  <tr>
<% end %>
  <td class="item-description"><%= line_item.quantity %>&times;</td>
  <td class="item-description"><%= line_item.product.title.truncate(40) %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

depot/app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.title, length: 50)) %>

depot/app/views/line_items/create.js.erb
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$("#cart").html("<%=j render(@cart) %>");
openCart();

//Add animation to highlight new item added to cart.
$('#current_item').css({
    "background-color":"#88ff88",
    "animation-name":"bckanim",
    "animation-fill-mode":"forwards",
    "animation-duration":"1s",
    "animation-delay":"0s"
})

depot/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/index.html.erb
<h1 id="title">Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

depot/app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

depot/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>